run_attack: False
num_vars: 10
num_nn_input: 6
num_nn_output: 3
steps: 30
step_size: 0.1
ode_step_size: 0.05
ode_order: 3
cut_off_threshold: 1e-6
remainder_estimation: [-0.01, 0.01]
initial_set:
  - {name: "x1", interval: [-0.45, -0.44]}
  - {name: "x2", interval: [-0.55, -0.54]}
  - {name: "x3", interval: [0.65, 0.66]}
  - {name: "x4", interval: [-0.75, -0.74]}
  - {name: "x5", interval: [0.85, 0.86]}
  - {name: "x6", interval: [-0.65, -0.64]}
  - {name: "t", interval: [0, 0]}
  - {name: "u1", interval: [0, 0]}
  - {name: "u2", interval: [0, 0]}
  - {name: "u3", interval: [0, 0]}
dynamics_expressions:
  - "0.25 * (u1 + x2 * x3)"
  - "0.5 * (u2 - 3 * x1 * x3)"
  - "u3 + 2 * x1 * x2"
  - "0.5 * (x2 * (x4^2 + x5^2 + x6^2 - x6) + x3 * (x4^2 + x5^2 + x5 + x6^2) + x1 * (x4^2 + x5^2 + x6^2 + 1))"
  - "0.5 * (x1 * (x4^2 + x5^2 + x6^2 + x6) + x3 * (x4^2 - x4 + x5^2 + x6^2) + x2 * (x4^2 + x5^2 + x6^2 + 1))"
  - "0.5 * (x1 * (x4^2 + x5^2 - x5 + x6^2) + x2 * (x4^2 + x4 + x5^2 + x6^2) + x3 * (x4^2 + x5^2 + x6^2 + 1))"
  - "1"
  - "0"
  - "0"
  - "0"
constraints_unsafe:
  - "-x1 - 0.2"
  - "x1"
  - "-x2 - 0.5"
  - "x2 + 0.4"
  - "-x3"
  - "x3 - 0.2"
  - "-x4 - 0.4"
  - "x4 + 0.6"
  - "-x5 + 0.7"
  - "x5 - 0.8"
  - "-x6 - 0.4"
  - "x6 + 0.2"
model_dir: "../ARCH-COMP2024/benchmarks/Attitude-Control/attitude_control_3_64_torch.onnx"
input_shape: [-1, 1, 6]
output_T_shape: [-1, 3, 6]
output_c_shape: [-1, 3]
output_scale: 1
output_offset: 0
bound_opts: {activation_bound_option: "same-slope"}
