run_attack: False
num_vars: 7
num_nn_input: 4
num_nn_output: 2
steps: 20
step_size: 0.05
ode_step_size: 0.01
ode_order: 4
cut_off_threshold: 1e-6
remainder_estimation: [-0.01, 0.01]
initial_set:
  - {name: "th1", interval: [1.0, 1.3], splits: 5}
  - {name: "th2", interval: [1.0, 1.3], splits: 5}
  - {name: "u1", interval: [1.0, 1.3], splits: 3}
  - {name: "u2", interval: [1.0, 1.3], splits: 3}
  - {name: "t", interval: [0, 0], splits: 0}
  - {name: "T1", interval: [0, 0], splits: 0}
  - {name: "T2", interval: [0, 0], splits: 0}
split_vars: ["th1", "th2", "u1", "u2"]
dynamics_expressions:
  - "u1"
  - "u2"
  - "4*T1 + 2*sin(th1) - (u2^2*sin(th1 - th2))/2 + (cos(th1 - th2)*(sin(th1 - th2)*u1^2 + 8*T2 + 2*sin(th2) - cos(th1 - th2)*(- (sin(th1 - th2)*u2^2)/2 + 4*T1 + 2*sin(th1))))/(2*(cos(th1 - th2)^2/2 - 1))"
  - "-(sin(th1 - th2)*u1^2 + 8*T2 + 2*sin(th2) - cos(th1 - th2)*(- (sin(th1 - th2)*u2^2)/2 + 4*T1 + 2*sin(th1)))/(cos(th1 - th2)^2/2 - 1)"
  - "1"
  - "0"
  - "0"
constraints_safe: ["-th1 - 1.7", "th1 - 2", "-th2 - 1.7", "th2 - 2", "-u1 - 1.7", "u1 - 2", "-u2 - 1.7", "u2 - 2"]
model_dir: "../ARCH-COMP2024/benchmarks/Double_Pendulum/controller_double_pendulum_less_robust.onnx"
input_shape: [-1, 4]
output_T_shape: [-1, 2, 4]
output_c_shape: [-1, 2]
output_scale: 1
output_offset: 0
bound_opts: {activation_bound_option: "same-slope"}
