run_attack: False
num_vars: 8
num_nn_input: 4
num_nn_output: 2
steps: 50
step_size: 0.2
ode_step_size: 0.02
ode_order: 2
cut_off_threshold: 1e-6
remainder_estimation: [-0.01, 0.01]
initial_set:
  - {name: "x1", interval: [9.5, 9.55]}
  - {name: "x2", interval: [-4.5, -4.45]}
  - {name: "x3", interval: [2.1, 2.11]}
  - {name: "x4", interval: [1.5, 1.51]}
  - {name: "w", interval: [-1e-4, 1e-4]}
  - {name: "t", interval: [0, 0]}
  - {name: "u1", interval: [0, 0]}
  - {name: "u2", interval: [0, 0]}
dynamics_expressions:
  - "x4 * cos(x3)"
  - "x4 * sin(x3)"
  - "u2 + w - 20"
  - "u1 + w - 20"
  - "0"
  - "1"
  - "0"
  - "0"
constraints_target: ["x1 - 0.6", "-x1 - 0.6", "x2 - 0.2", "-x2 - 0.2", "x3 - 0.06", "-x3 - 0.06", "x4 - 0.3", "-x4 - 0.3"]
model_dir: "../ARCH-COMP2024/benchmarks/Benchmark10-Unicycle/controllerB.onnx"
input_shape: [-1, 1, 1, 4]
output_T_shape: [-1, 2, 4]
output_c_shape: [-1, 2]
output_scale: 1
output_offset: 0
bound_opts: {activation_bound_option: "same-slope"}
